### ISSUE TITLE
Class 'Protobuf\\Identity\\AuthServiceClient' not found

### ISSUE THREAD

**Issue by ahmadateya** [roseffendi/laravel-grpc-client#1]
when I tried to use the register endpoint it gives me this error
`    "message": "Class 'Protobuf\\Identity\\AuthServiceClient' not found",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "file": "/home/ateya/Desktop/projects/laravel-grpc-client/app/Services/Grpc/ConfigurableClientFactory.php",
    "line": 41,
`
I know the AuthServiceClient file is not there, but why?
Am I missing something to run the project?

**Comment by vanushwashere** [comment]
You should run `composer require google/protobuf`

**Comment by roseffendi** [comment]
Sorry, i'm so late to reply your question. In case it helps I'll answer it.

You have to compile the proto files to generate that class. The sample how to compile the files is in app.dockerfile. Generated files are intentionally not included to the repository.

**Comment by vanushwashere** [comment]
You generated grpc_php_plugin executable via Make from `grpc/grpc` source ?
